### ISSUE TITLE
Generate only specific protos

### ISSUE THREAD

**Issue by 0xC0D3D00D** [bufbuild/protoschema-plugins#47]
Hello!

Thank you for the great work. I'm working on a project that only a few of the protos are used for the pubsub. I'd like to generate pubsub scheme only for those protos but it generates it also for all its subtypes. What I did is to create a separate generation template `buf.pubsub.gen.yaml` not to generate pubsub inlines for all the protos yet I couldn't exclude the sub types.

buf.yaml
```yaml
version: v2

managed:
    enabled: true
    disable:
      - file_option: go_package
        module: buf.build/googleapis/googleapis
      - file_option: go_package
        module: buf.build/protocolbuffers/wellknowntypes
    override:
      - file_option: go_package_prefix
        value: example.com/theproject/packages/go/proto

plugins:
  - remote: buf.build/protocolbuffers/go:v1.36.4
    out: packages/go/proto
    opt: paths=source_relative
  - remote: buf.build/grpc/go:v1.5.1
    out: packages/go/proto
    opt: paths=source_relative
```

buf.pubsub.gen.yaml
```yaml
version: v2

managed:
    enabled: true

plugins:
  - remote: buf.build/bufbuild/protoschema-pubsub
    out: gen/proto/infra/pubsub
    include_imports: false
    include_wkt: false

inputs:
  - directory: proto
    types:
      - "com.example.eventsystem.event.v1.Event"
```

Proto directory structure:
```
proto
└── org
    └── example
        └── eventsystem
            └── event
                └── v1
                    ├── event.proto
                    ├── event_type.proto
                    └── service.proto
```

Generated proto:
```
gen
└── proto
    └── infra
        └── pubsub
            ├── com.example.eventsystem.event.v1.Event.pubsub.proto
            ├── com.example.eventsystem.event.v1.EventDataEvent1.pubsub.proto
            ├── com.example.eventsystem.event.v1.EventDataEvent2.pubsub.proto
            ├── com.example.eventsystem.event.v1.EventDataEvent3.pubsub.proto
            ├── com.example.eventsystem.event.v1.EventDataEvent4.pubsub.proto
            ├── com.example.eventsystem.event.v1.EventDataEvent5.pubsub.proto
            └── com.example.eventsystem.event.v1.EventDataEvent6.pubsub.proto
```

From these I only need `com.example.eventsystem.event.v1.Event.pubsub.proto`, Is it possible to only generate this one?
